# whitelist
branches:
  only:
    - master
    - gh-pages

# environment variables
env:
  - R_LIBS_USER=~/R

# install dependencies
install:
  - sudo apt-add-repository -y ppa:marutter/rdev
  - sudo apt-get update
  - sudo apt-get install cabal-install
  - cabal update
  - PATH=$HOME/.cabal/bin:$PATH
  - cabal install alex happy
  - cabal install pandoc pandoc-citeproc
  - which pandoc
  - pandoc --version
  - sudo apt-get install r-base
  - "[ ! -d ~/R ] && mkdir ~/R"
  - R --version
  - Rscript -e '.libPaths(); sessionInfo()'
  - Rscript -e 'install.packages(c("rmarkdown", "devtools"), type = "source", repos = "http://cran-r.c3sl.ufpr.br/")'
  - Rscript -e 'devtools::install_github("yihui/knitr")'

# build site
script:
  - make
